export const homeObjOne = {
    id: 'about',
    background: 'bg-base-100',
    fontcolor: 'text-base-content',
    topLine: 'UNLIMITED FITNESS',
    topLineColor: 'text-secondary',
    headline: 'Unlimited Workouts with Zero Limits',
    description: 'Get access to our exclusive app that allows you to create and track unlimited workouts without any restrictions.',
    buttonLabel: 'Get Started',
    buttonColor: 'btn-primary',
    target: '/signup',
    imgStart: false,
    img: 'images/homePage/svg-1.svg',
    alt: 'Fitness tracker',
};

export const homeObjTwo = {
    id: 'discover',
    background: 'bg-primary-content',
    fontcolor: 'text-base-100',
    topLine: 'YOUR WORKOUT, YOUR RULES',
    topLineColor: 'text-primary',
    headline: 'Discover Your Perfect Workout',
    description: 'Find the perfect workout routine that fits your schedule and helps you reach your fitness goals.',
    buttonLabel: 'Learn More',
    buttonColor: 'btn-secondary',
    target: '/signup',
    imgStart: true,
    img: 'images/homePage/svg-2.svg',
    alt: 'Workout tracker',
};

export const homeObjThree = {
    id: 'signup',
    background: 'bg-primary-content',
    fontcolor: 'text-base-100',
    topLine: 'JOIN OUR COMMUNITY',
    topLineColor: 'text-primary',
    headline: 'Creating your account is super easy',
    description: `Get everything set up and start tracking your workouts in under 10 minutes. Just enter your details and you're ready to begin your fitness journey.`,
    buttonLabel: 'Start Now',
    buttonColor: 'btn-secondary',
    target: '/signup',
    imgStart: false,
    img: 'images/homePage/svg-6.svg',
    alt: 'Activity tracker',
};